version: '3'

services:
  app:
    container_name: app
    build: .
    ports:
      - "5000:5000"
    links:
      - db:db
    environment:
      - FLASK_CONFIG=dev
      - DATABASE_URL=postgresql://mountain:mountain@db:5432/mountain_pics_db
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    container_name: db
    image: postgres:12
    expose:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - mountain-db:/var/lib/postgresql/data

volumes:
  mountain-db: {}
