version: '3.9'

services:
  db:
    image: postgres:latest
    volumes:
      - mountain-db:/var/lib/postgresql/data
    environment:
      POSTGRES_PORT: 5432
      POSTGRES_USER: mountain_pics_user
      POSTGRES_PASSWORD: mountain_pics_pwd
      POSTGRES_DB: mountain_pics_db
    expose:
      - "5432:5432"
  app:
    build: .
    links:
      - db:db
    environment:
      FLASK_CONFIG: dev
      DATABASE_URL: postgresql://mountain_pics_user:mountain_pics_pwd@db:5432/mountain_pics_db
    volumes:
      - .:/app
    depends_on:
      - db
    ports:
      - "5000:5000"
    entrypoint: ["run", "flask", "init_db"]
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:5000/healthcheck || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  mountain-db:
